
name: GitHub Actions Learning
on: [ push ]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
       -run: "echo "This job was automatically triggered by a ${{github.push}} event"
      - run: "python main.py"